[package]
name = "nib"
description = "A GUI text editor with nano's interaction model."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
default-run = "nib"

[dependencies]
nib-core = { workspace = true }
nib-ui = { workspace = true }
