[package]
name = "aitch"
description = "A GUI text editor with nano's interaction model."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
default-run = "aitch"

[dependencies]
aitch-core = { workspace = true }
aitch-ui = { workspace = true }
